apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kvm-server

resources:
  - namespace.yaml
  - mysql-secret.yaml
  - mysql-configmap.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - backend-configmap.yaml
  - backend-secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - nginx-deployment.yaml
  - ingress.yaml
