apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: kvm-server
type: Opaque
stringData:
  mysql-root-password: rootpassword
  mysql-database: kvm_db
  mysql-user: kvm_user
  mysql-password: kvm_password
